### ISSUE TITLE
1.21.3 Support

### ISSUE THREAD

**Issue by JoshuaVandaele** [umjammer/JustMap#6]
I'd love to see 1.21.3 support if possible, currently launching the latest jar on 1.21.3 crashes the game.

I'd also like to thank the community for this fork, I didn't think any recent version of minecraft had an open source minimap mod!

Underneath are the logs relevant to the crash

<details>

```

  [04:37:08] [main/ERROR]: Mixin apply for mod justmap failed justmap.mixins.json:RedstoneLevelAccessor from mod justmap -> net.minecraft.class_2457: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_24466:[Lnet/minecraft/class_243; in net/minecraft/class_2457 for justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243; [ACCESSOR Applicator Phase -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap -> Apply Accessors ->  -> Locate -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243;]
  org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_24466:[Lnet/minecraft/class_243; in net/minecraft/class_2457 for justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243; [ACCESSOR Applicator Phase -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap -> Apply Accessors ->  -> Locate -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243;]
	  at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1517) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:761) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.7.jar:?]
	  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	  at knot/net.minecraft.class_2246.<clinit>(class_2246.java:347) [client-intermediary.jar:?]
	  at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
	  at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) [client-intermediary.jar:?]
	  at knot/net.minecraft.client.main.Main.main(Main.java:138) [client-intermediary.jar:?]
	  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
	  at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	  at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	  at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
  [04:37:08] [main/WARN]: Failed to get system info for GL Caps
  java.lang.IllegalStateException: Rendersystem called from wrong thread
	  at knot/com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:139) ~[client-intermediary.jar:?]
	  at knot/com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:134) ~[client-intermediary.jar:?]
	  at knot/com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:478) ~[client-intermediary.jar:?]
	  at knot/net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
	  at knot/net.minecraft.class_310.method_37274(class_310.java:2493) [client-intermediary.jar:?]
	  at knot/net.minecraft.class_310.method_22681(class_310.java:2463) [client-intermediary.jar:?]
	  at knot/net.minecraft.client.main.Main.main(Main.java:219) [client-intermediary.jar:?]
	  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
	  at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	  at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	  at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-11-03 04:37:08
Description: Bootstrap

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2457 failed
	at knot//net.minecraft.class_2246.<clinit>(class_2246.java:347)
	at knot//net.minecraft.class_2358.method_10199(class_2358.java:336)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2457 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [justmap.mixins.json:RedstoneLevelAccessor from mod justmap] from phase [DEFAULT] in config [justmap.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_24466:[Lnet/minecraft/class_243; in net/minecraft/class_2457 for justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243; [ACCESSOR Applicator Phase -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap -> Apply Accessors ->  -> Locate -> justmap.mixins.json:RedstoneLevelAccessor from mod justmap->@Accessor[FIELD_GETTER]::getPowerVectors()[Lnet/minecraft/class_243;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1517)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:761)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at knot//net.minecraft.class_2246.<clinit>(class_2246.java:347)
	at knot//net.minecraft.class_2358.method_10199(class_2358.java:336)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

</details>

**Comment by umjammer** [comment]
wait just a little bit more.

it's too fast to catch up with mc version up.
i missed 1.21.2 during i'm into street fighter 6...

tell me a good rss for mc version up.

**Comment by JoshuaVandaele** [comment]
I think the MinecraftForum News RSS feed might be what you're looking for: http://www.minecraftforum.net/news.rss

1.21.3 was a hotfix for 1.21.2, don't worry too much. Keep up the good work :heart:

**Comment by umjammer** [comment]
released

https://github.com/umjammer/JustMap/releases/tag/mc-1.21.3

and thanks for the good rss 😀
