### ISSUE TITLE
[1.21.4] custom skin on worldmap cannot be loaded

### ISSUE THREAD

**Issue by umjammer** [umjammer/JustMap#7]
<img width="574" alt="2024-12-08 14 48 00" src="https://github.com/user-attachments/assets/3ea17702-0cd9-432c-97ec-084b86d97f9f">

https://github.com/umjammer/JustMap/compare/1.21.3...umjammer:JustMap:1.21.4#diff-cc601e8caab991b86c1aaf804dedd13568e27959ad0d59c23cb737bf167cea71R108-R117

```
[12:15:45] [Render thread/ERROR]: Failed to load texture null into slot null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12836()" because "$$0" is null
	at knot/net.minecraft.class_6861.method_14486(class_6861.java:79) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3304.method_14486(class_3304.java:52) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10539.method_65871(class_10539.java:19) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1049.method_65809(class_1049.java:15) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_65877(class_1060.java:184) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_65925(class_1060.java:63) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_65876(class_1060.java:49) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_4619(class_1060.java:109) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:674) ~[client-intermediary.jar:?]
	at knot/ru.bulldog.justmap.util.render.RenderUtil.bindTexture(RenderUtil.java:81) ~[justmap-1.2.459-1.21.4-release.jar:?]
	at knot/ru.bulldog.justmap.map.icon.PlayerHeadIconImage.draw(PlayerHeadIconImage.java:50) ~[justmap-1.2.459-1.21.4-release.jar:?]
	at knot/ru.bulldog.justmap.client.screen.WorldmapScreen.renderForeground(WorldmapScreen.java:198) ~[justmap-1.2.459-1.21.4-release.jar:?]
	at knot/ru.bulldog.justmap.client.screen.AbstractJustMapScreen.method_25394(AbstractJustMapScreen.java:58) ~[justmap-1.2.459-1.21.4-release.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:116) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$74(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$zmg000$fabric-screen-api-v1$onRenderScreen(class_757.java:914) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:551) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1341) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:922) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
```

**Comment by umjammer** [comment]
crash has fixed by 6b762a2
but skin is still not loaded

**Comment by umjammer** [comment]
https://github.com/NiFeather/FeatherMorph/blob/1.21.4/src/main/java/xyz/nifeather/morph/misc/skins/PlayerSkinProvider.java#L29
